pipeline {
    agent any   // Jenkins 어느 노드에서든 실행

    stages {
        stage('Checkout') {
            steps {
                echo 'Cloning Repository'
                // GitLab master 브랜치 소스 코드 가져오기
                git branch: 'master',
                    url: 'https://lab.ssafy.com/s13-bigdata-recom-sub1/S13P21C102.git',
                    credentialsId: 'credential_002seojin'
            }
        }

        stage('Build') {
            steps {
                dir('picky-be') {
                    echo 'Building Spring Boot JAR'
                    sh './gradlew clean build -x test'
                }
            }
        }

        stage('Deploy') {
            when {
                branch 'master'
            }
            steps {
                echo 'Deploy with Docker Compose'
                 dir('picky-be') {
                      withCredentials([file(credentialsId: 'env_secretfile_credential', variable: 'ENV_FILE')]) {
                        sh '''
                             set -eu
                             cp "$ENV_FILE" .env
                             chmod 600 .env
                             docker compose down
                             docker compose up -d --build
                        '''
                      }
                 }
            }
        }
    }
}
